name: Eureka Server JAR

on:
  push:
    branches:
      - master   # runs only when code is pushed to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'   # adjust if your project uses a different version
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: eureka-jar
          path: target/*.jar
